**[SF-DST] Car Price prediction**

**Прогнозирование стоимости автомобиля по характеристикам**

Команда: 4BI

Члены команды: Икен Шынгысхан, Нурсейт Бекзат, Амангелди Ильяс

### В этом ноутбуке проверялись разные алгоритмы с подсчетом МАРЕ на валидационных данных.

In [2]:
import pandas as pd
import numpy as np

In [3]:
import xgboost as xgb

In [4]:
X_train = pd.read_csv('x_train.csv')
X_test = pd.read_csv('x_test.csv')
Y_train = pd.read_csv('y_train.csv')

In [ ]:
xgb_model = xgb.XGBRFRegressor(n_estimators=2500, max_depth=30, random_state=42).fit(X_train, Y_train)

[11:28:27] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


In [ ]:
pred = xgb_model.predict(X_test)

In [ ]:
sample_submission = pd.read_csv('sample_submission.csv')
sample_submission['price'] = pred
sample_submission['price'] = sample_submission['price'].fillna(sample_submission['price'].mean())
sample_submission.to_csv(f'submission_12.csv', index=False)

In [ ]:
s = pd.read_csv('submission_11.csv')

In [ ]:
pred

array([320607.53, 504551.53, 403362.6 , ..., 119353.57, 709960.06,
       480771.03], dtype=float32)

In [ ]:
pred

array([ 644978.9 , 1012093.94,  807332.75, ...,  238158.73, 1420664.2 ,
        966930.5 ], dtype=float32)

In [ ]:
pred

array([ 645237.5 , 1011341.4 ,  808591.1 , ...,  238521.77, 1421100.4 ,
        967831.2 ], dtype=float32)

In [5]:
df = pd.read_csv('kaggle_cars.csv', encoding='utf-8')

In [6]:
df['log_price'] = np.log(df['Цена'])

In [7]:
df['mileage'] = np.log(df['mileage'])

In [8]:
df['engineDisplacement'] = np.log(df['engineDisplacement'])

In [9]:
df['enginePower'] = np.log(df['enginePower'])

In [10]:
df = df.drop('Цена', axis=1)

In [11]:
test = pd.read_csv('test.csv')

In [12]:
combined = pd.concat([df, test], ignore_index=True)

In [13]:
df = df.drop('Владельцы', axis=1)
df = df.drop('Владение', axis=1)

In [14]:
df['ПТС'] = df['ПТС'].fillna('Оригинал')

In [15]:
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

In [16]:
df['Руль'] = pd.Series(LabelEncoder().fit_transform(df['Руль']))

In [17]:
df['bodyType'] = pd.Series(LabelEncoder().fit_transform(df['bodyType']))

In [18]:
df['brand'] = pd.Series(LabelEncoder().fit_transform(df['brand']))

In [19]:
df['color'] = pd.Series(LabelEncoder().fit_transform(df['color']))

In [20]:
df['fuelType'] = pd.Series(LabelEncoder().fit_transform(df['fuelType']))

In [21]:
df['model_name'] = pd.Series(LabelEncoder().fit_transform(df['model_name']))

In [22]:
df['vehicleTransmission'] = pd.Series(LabelEncoder().fit_transform(df['vehicleTransmission']))

In [23]:
df['ПТС'] = pd.Series(LabelEncoder().fit_transform(df['ПТС']))

In [24]:
df['Привод'] = pd.Series(LabelEncoder().fit_transform(df['Привод']))

In [25]:
df['Состояние'] = pd.Series(LabelEncoder().fit_transform(df['Состояние']))

In [26]:
df['Таможня'] = pd.Series(LabelEncoder().fit_transform(df['Таможня']))

In [27]:
from sklearn.model_selection import train_test_split, KFold

In [28]:
X = df.iloc[:,:-1]
Y = df['log_price']

In [29]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.3)

In [30]:
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor

In [31]:
def mape(y_true, y_pred):
    return np.mean(np.abs((y_pred-y_true)/y_true))

In [32]:
model = GradientBoostingRegressor(learning_rate=0.01, max_depth=15, n_estimators=2000, random_state=42)

In [33]:
model.fit(X_train, Y_train)

GradientBoostingRegressor(alpha=0.9, ccp_alpha=0.0, criterion='friedman_mse',
                          init=None, learning_rate=0.01, loss='ls',
                          max_depth=15, max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=2000,
                          n_iter_no_change=None, presort='deprecated',
                          random_state=42, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [34]:
y_pred = model.predict(X_test)

In [35]:
mape(np.exp(Y_test), np.exp(y_pred))

0.16585826469787374

In [ ]:
model = DecisionTreeRegressor(max_depth = 18, random_state = 42)

In [ ]:
model.fit(X_train, Y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=18,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=42, splitter='best')

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
mape(Y_test, y_pred)

0.013841956578066604

In [ ]:
model = RandomForestRegressor(n_estimators=2000, max_depth = 15, random_state = 42)

In [ ]:
model.fit(X_train, Y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=15, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=2000, n_jobs=None, oob_score=False,
                      random_state=42, verbose=0, warm_start=False)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
mape(np.exp(Y_test), np.exp(y_pred))

0.14323044830580117

In [48]:
model = RandomForestRegressor(n_estimators=2000, max_depth = 17, random_state = 42)

In [49]:
model.fit(X_train, Y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=17, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=500, n_jobs=None, oob_score=False,
                      random_state=42, verbose=0, warm_start=False)

In [50]:
y_pred = model.predict(X_test)

In [51]:
mape(np.exp(Y_test), np.exp(y_pred))

0.14004576717660433

In [178]:
xgb_model = xgb.XGBRFRegressor(n_estimators=2000, max_depth=15, random_state=42)

In [179]:
xgb_model.fit(X_train, Y_train)

[17:46:58] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRFRegressor(base_score=0.5, colsample_bylevel=1, colsample_bynode=0.8,
               colsample_bytree=1, gamma=0, learning_rate=1, max_delta_step=0,
               max_depth=15, min_child_weight=1, missing=None,
               n_estimators=2000, n_jobs=1, nthread=None,
               objective='reg:linear', random_state=42, reg_alpha=0,
               reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
               subsample=0.8, verbosity=1)

In [180]:
y_pred = model.predict(X_test)

In [181]:
mape(np.exp(Y_test), np.exp(y_pred))

0.14343178729715367

In [ ]:
X_train

bodyType  brand  color  ...  Руль  Состояние  Таможня
19765         1      7      5  ...     0          1        0
20990        21      8      1  ...     0          1        0
13951        15      1     15  ...     0          1        0
2128         15      2      7  ...     1          1        0
15710        15      4     15  ...     0          1        0
...         ...    ...    ...  ...   ...        ...      ...
7033          1      0      6  ...     0          1        0
28830        15      5     12  ...     0          1        0
7635         15      0     13  ...     0          1        0
2829         15      2     11  ...     0          1        0
15917        15      4      6  ...     0          1        0

[22837 rows x 15 columns]